{
    "swagger": "2.0",
    "info": {
        "version": "0.0.1",
        "title": "Openlab API",
        "description": "This is the OpenLab API",
        "termsOfService": "http://open-lab.io/terms/",
        "contact": {
            "name": "apiteam@open-lab.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "host": "api.open-lab.io",
    "basePath": "/v1",
    "schemes": [
        "http",
        "https"
    ],
    "security": [
        {
            "openLabImplicit": [
                "user",
                "user:email",
                "read:post",
                "write:post",
                "comment:post",
                "read:group",
                "post:group",
                "admin:group"
            ]
        }
    ],
    "securityDefinitions": {
        "openLabImplicit": {
            "type": "oauth2",
            "authorizationUrl": "http://api.open-lab.io/api/oauth/dialog",
            "flow": "implicit",
            "scopes": {
                "user": "Grants read/write access to profile info, includes user:email",
                "user:email": "Grants read access to a user's email addresses.",
                "read:post": "Grants read access to a post",
                "write:post": "Grants write access to a post, allowing to change the contents",
                "comment:post": "Grants comment access to a post, allowing to create comments on a post",
                "read:group": "Grants read access to a group, allowing to see all posts and users",
                "post:group": "Grants write access to a groups' posts, allowing the user to create new posts in the group",
                "admin:group": "Grants admin access to a group, allowing to add and remove users to it, as well as inviting other users"
            }
        }
    },
    "paths": {
        "/groups": {
            "post": {
                "summary": "Create a new group",
                "tags": [
                    "group"
                ],
                "description": "Allows you to create a new `Group` object\n",
                "operationId": "addGroup",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group"
                        ]
                    }
                ]
            },
            "get": {
                "summary": "Get all groups",
                "operationId": "getGroups",
                "description": "Gets `Group` objects.\nOptional query param of **size** determines\nsize of returned array\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}": {
            "get": {
                "tags": [
                    "group"
                ],
                "summary": "Find group by ID",
                "description": "Returns a group with the specified id\n",
                "operationId": "getGroupById",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "group"
                ],
                "summary": "Update an existing group",
                "description": "Updates a group given an id\n",
                "operationId": "updateGroupById",
                "security": [
                    {
                        "openLabImplicit": [
                            "admin:group"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}/posts": {
            "get": {
                "tags": [
                    "post"
                ],
                "summary": "Gets all posts for a group",
                "operationId": "getPosts",
                "description": "Gets all posts on a given group. In order to query for posts,\nyou can provide an offset, and the number of posts to return (defaults to 10).\nPosts are returned in chronological order.\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group",
                            "read:post"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "post"
                ],
                "summary": "Add a new post to the store",
                "operationId": "addPost",
                "description": "Adds a new post to the store, requires\nthe user to have rights to post to the\ngroup\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "admin:group",
                            "write:post",
                            "read:post"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}/posts/{postId}": {
            "get": {
                "tags": [
                    "post"
                ],
                "summary": "Get post by ID",
                "description": "Gets a post given an ID, provided the user\nhas read rights to the group the post belongs to\n",
                "operationId": "getPostById",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group",
                            "read:post"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "post"
                ],
                "summary": "Update a post by ID",
                "operationId": "updatePostById",
                "description": "Allows updating a post by passing the\nid as part of the path\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group",
                            "admin:group",
                            "write:post",
                            "read:post"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "post"
                ],
                "summary": "Deletes a Post given an id",
                "operationId": "deletePostById",
                "description": "If given an id of a valid post that the user\nhas write rights to, it will be deleted from the\nstore\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group",
                            "admin:group",
                            "write:post",
                            "read:post"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}/posts/findByTags": {
            "get": {
                "summary": "Finds posts by tag",
                "description": "Multiple tags can be passed with comma-separated strings\n",
                "operationId": "findPostsByTags",
                "tags": [
                    "post",
                    "tag"
                ],
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group",
                            "read:post"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}/posts/findByAuthor": {
            "get": {
                "summary": "Finds posts by author",
                "description": "Finds posts for an author\n",
                "operationId": "findPostsByAuthorId",
                "tags": [
                    "post",
                    "user"
                ],
                "security": [
                    {
                        "openLabImplicit": [
                            "read:post"
                        ]
                    }
                ]
            }
        },
        "/groups/{groupId}/users": {
            "get": {
                "summary": "Get all the users in a group",
                "description": "By passing a group id, returns all users\nthat are members of a group\n",
                "operationId": "getUsersByGroup",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            }
        },
        "/groups/{groupId}/groups": {
            "get": {
                "summary": "Get all children groups for a given group",
                "operationId": "getChildrenForGroup",
                "description": "Gets all children of the specified\ngroup up to a maximum level of recursion.\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "read:group"
                        ]
                    }
                ]
            }
        },
        "/users": {
            "post": {
                "summary": "creates a new User",
                "description": "This creates a new user. It requires a valid\ninvitation token, which is generated at the\ninvitation step\n",
                "operationId": "createUser",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            }
        },
        "/users/{userId}": {
            "get": {
                "summary": "gets a user by ID",
                "description": "Finds a user by ID",
                "operationId": "getUserById",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            },
            "put": {
                "summary": "updates a user by ID",
                "description": "Updates a user given an ID",
                "operationId": "updateUserById",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            }
        },
        "/users/findByName": {
            "get": {
                "summary": "gets users by name",
                "description": "search for a user by name",
                "operationId": "getUsersByName",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            }
        },
        "/users/findByInstitution": {
            "get": {
                "summary": "gets users for an institution",
                "description": "lists all users that belong to a given institution",
                "operationId": "getUsersByInstitution",
                "security": [
                    {
                        "openLabImplicit": [
                            "user"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            }
        },
        "/users/login": {
            "post": {
                "summary": "logs the user in",
                "description": "This endpoint allows a user to login onto the system\n",
                "operationId": "loginUser",
                "tags": [
                    "user"
                ]
            }
        },
        "/users/logout": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Logs out the currently logged in user session",
                "description": "",
                "operationId": "logoutUser"
            }
        },
        "/groups/{groupId}/invitations": {
            "post": {
                "summary": "Creates an invitation",
                "description": "This endpoint allows users with admin rights to a group to\nto invite users to openLab\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "user",
                            "admin:group"
                        ]
                    }
                ],
                "tags": [
                    "user",
                    "group"
                ]
            }
        },
        "/groups/{groupId}/invitations/{invitationId}": {
            "get": {
                "summary": "Gets an Invitation",
                "description": "Gets an Invitation\n",
                "security": [
                    {
                        "openLabImplicit": [
                            "user",
                            "admin:group"
                        ]
                    }
                ],
                "tags": [
                    "user"
                ]
            },
            "put": {
                "summary": "Updates an Invitation",
                "description": "Used to update the Invitation once it's accepted\n"
            }
        }
    }
}